on: push
name: Construir imagen de docker y subirla a dockerhub
jobs:
  build-push:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Clonar y checkout de la rama actual

    - name: Build y push la imagen
      uses: HurricanKai/Publish-Docker-Github-Action@master
      with:
        name: maditoidealismo/github-actions
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile
