name: Construir imagen de docker y subirla a dockerhub
on:
  push:
    branches:
      - master
jobs:
  build-push:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: Build y push de la imagen de docker a dockerhub
        uses: HurricanKai/Publish-Docker-Github-Action@master
        with:
          name: malditoidealismo/github-actions
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          #dockerfile: Dockerfile
  deploy-server:
    needs: build-push
    runs-on: ubuntu-18.04
    steps:
      - name: Conectarse via ssh a server y correr imagen de docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: echo ${{ secrets.PASSWORD }} | sudo -S apt update && 
                  echo ${{ secrets.PASSWORD }} | sudo -S apt install docker.io -y &&
                  echo ${{ secrets.PASSWORD }} | sudo -S docker rmi -f malditoidealismo/github-actions:latest &&
                  echo ${{ secrets.PASSWORD }} | sudo -S docker rm -f hola-mundo &&
                  echo ${{ secrets.PASSWORD }} | sudo -S docker run -p 3000:3000 -dit --name="hola-mundo" malditoidealismo/github-actions:latest
