name: Construir imagen de docker y subirla a dockerhub
on:
  push:
    branches:
      - master
jobs:
  build-push:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Build y push de la imagen de docker a dockerhub
        uses: HurricanKai/Publish-Docker-Github-Action@master
        with:
          name: malditoidealismo/github-actions
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          #dockerfile: Dockerfile
  deploy-server:
    runs-on: ubuntu-18.04
    steps:
      - uses: appleboy/ssh-action@master
      - name: Conectarse via ssh a server y correr imagen de docker
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: echo ${{ secrets.PASSWORD }} | sudo -S apt update && apt install docker.io -y && docker run malditoidealismo/github-actions:latest
